### ISSUE TITLE
Light component declaration

### ISSUE THREAD

**Issue by tony-go** [bcomnes/lighterhui#1]
I just think about that :)

```javascript
const component = new Component((name) => html`<div>${name}</div>`)
```

Let me know if Im out of scope :)

**Comment by bcomnes** [comment]
The shorthand syntax would cover this well enough no?

**Comment by tony-go** [comment]
It's lack of understanding from me, sorry for that.

I try this, and that's work very fine :)

```javascript
const { Component } = require('lighterhui')

const el = new Component({
  createElement() {
    return this.html`<h1>someDomElement</h1>`
  }
})
```

I don't know why, but when I read the documentation the first time I though that other methods (render, onload ...) was required :/

**Comment by bcomnes** [comment]
Np, that could be better clarified.
